import { CommonModule } from '@angular/common';
import { Component, NgZone, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LocalNotifications } from '@capacitor/local-notifications';
import { IonicModule } from '@ionic/angular';

@Component({
  selector: 'app-local-notifications-page',
  standalone: true,
  imports: [CommonModule, IonicModule, FormsModule],
  templateUrl: './local-notifications-page.component.html',
  styleUrls: ['./local-notifications-page.component.scss'],
})
export class LocalNotificationsPageComponent implements OnInit {
  message = '';
  triggered = false;
  scheduled = false;

  constructor(private ngZone: NgZone) {}

  ngOnInit() {
    // When the user taps on the notification
    LocalNotifications.addListener('localNotificationActionPerformed', notif => {
      console.log(notif);
      this.ngZone.run(() => {
        this.triggered = true;
        this.scheduled = false;
      });
    });
  }

  async createNotification() {
    await LocalNotifications.schedule({
      notifications: [
        {
          id: 1, // Unique id
          title: this.message,
          body: 'This is a local notification generated by Capacitor',
          schedule: { at: new Date(new Date().getTime() + 10000) },
        }
      ]
    });
    this.scheduled = true;
    this.triggered = false;
  }

  async cancelNotification() {
    try {
      await LocalNotifications.cancel(await LocalNotifications.getPending());
    } finally {
      this.scheduled = false;
    }
  }

  ngOnDestroy() {
    LocalNotifications.removeAllListeners();
  }

}
